In [1]:
# Step 1 — Import libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
# Step 2 — Load dataset

df = pd.read_csv(r"C:\ddrive\jpmorgan\banking-data-portfolio\credit-risk-model\data\credit_risk_dataset.csv")

df.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [3]:
# Step 3 — Understand dataset

df.info()

df.describe()

# Check missing values:

df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_grade                  32581 non-null  str
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  str
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.0 MB

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [4]:
# Step 4 — Select relevant features

df_model = df[
    [
        "person_age",
        "person_income",
        "loan_amnt",
        "loan_int_rate",
        "loan_percent_income",
        "cb_person_default_on_file",
        "cb_person_cred_hist_length",
        "loan_status"
    ]
]

In [5]:
# Step 5 — Convert categorical variables

df_model = pd.get_dummies(df_model, drop_first=True)

In [6]:
# Step 6 — Define X and y

X = df_model.drop("loan_status", axis=1)

y = df_model["loan_status"]

In [7]:
# Step 7 — Train test split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

In [8]:
# check missing values

print(df_model.isnull().sum())

person_age                        0
person_income                     0
loan_amnt                         0
loan_int_rate                  3116
loan_percent_income               0
cb_person_cred_hist_length        0
loan_status                       0
cb_person_default_on_file_Y       0
dtype: int64

In [9]:
print(X.dtypes)

person_age                       int64
person_income                    int64
loan_amnt                        int64
loan_int_rate                  float64
loan_percent_income            float64
cb_person_cred_hist_length       int64
cb_person_default_on_file_Y       bool
dtype: object

In [10]:
# Step 7 — Train test split

from sklearn.model_selection import train_test_split

X = df_model.drop("loan_status", axis=1)
y = df_model["loan_status"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

In [11]:
# clean training data
X_train = X_train.fillna(0)

# clean test data
X_test = X_test.fillna(0)

In [12]:

print(X_test.isnull().sum())

person_age                     0
person_income                  0
loan_amnt                      0
loan_int_rate                  0
loan_percent_income            0
cb_person_cred_hist_length     0
cb_person_default_on_file_Y    0
dtype: int64

In [13]:
# Step 8 — Train Logistic Regression model

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=500)

model.fit(X_train, y_train)

LogisticRegression(max_iter=500)

In [14]:
# Step 9 — Make predictions

y_pred = model.predict(X_test)

y_prob = model.predict_proba(X_test)[:,1]

In [15]:
# Step 10 — Evaluate model

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8219948849104859

In [16]:
# Confusion matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[7314  299]
 [1441  721]]

In [17]:
# Classification report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.96      0.89      7613
           1       0.71      0.33      0.45      2162

    accuracy                           0.82      9775
   macro avg       0.77      0.65      0.67      9775
weighted avg       0.81      0.82      0.80      9775

In [18]:
# Step 11 — Feature importance

importance = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model.coef_[0]
})

importance.sort_values(by="Coefficient", ascending=False)

                       Feature  Coefficient
4          loan_percent_income    10.069521
6  cb_person_default_on_file_Y     0.654829
3                loan_int_rate     0.125325
0                   person_age     0.003450
1                person_income    -0.000003
2                    loan_amnt    -0.000061
5   cb_person_cred_hist_length    -0.003203

In [19]:
# Step 12 — Predict default probability for customers

results = X_test.copy()

results["actual"] = y_test

results["predicted"] = y_pred

results["default_probability"] = y_prob

results.head()

,person_age,person_income,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,cb_person_default_on_file_Y,actual,predicted,default_probability
14668,24,28000,10000,10.37,0.36,2,False,0,1,0.579773
24614,27,64000,10000,15.27,0.16,10,True,0,0,0.364591
11096,26,72000,16000,0.00,0.22,3,False,0,0,0.052452
10424,23,27996,10000,0.00,0.36,2,False,1,0,0.272651
26007,30,44500,13000,16.32,0.29,6,False,1,1,0.533289

In [20]:
# Step 13 — Business insight example -Example interpretation:

# Customers with:

# high loan amount
# high interest rate
# low income

# have higher probability of default.

In [21]:
# Step 14 — Save model results

results.to_csv(
    "../data/credit_risk_predictions.csv",
    index=False
)